apiVersion: apps/v1
kind: Deployment
metadata:
  name: seoulfit
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: seoulfit
  template:
    metadata:
      labels:
        app: seoulfit
    spec:
      containers:
      - name: seoulfit
        image: seoulfit:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        # Secret에서 환경변수 가져오기
        envFrom:
        - secretRef:
            name: seoulfit-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: seoulfit-service
spec:
  selector:
    app: seoulfit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
# Secret 생성 예시 (실제로는 kubectl로 생성)
apiVersion: v1
kind: Secret
metadata:
  name: seoulfit-secrets
type: Opaque
stringData:
  SEOUL_API_KEY: "your-seoul-api-key"
  KAKAO_CLIENT_ID: "your-kakao-client-id"
  KAKAO_CLIENT_SECRET: "your-kakao-client-secret"
  DB_PASSWORD: "your-db-password"
  JWT_SECRET: "your-jwt-secret-minimum-32-characters"