name: "♻️ Refactoring"
description: "코드 리팩토링 작업"
labels: ["♻️ refactor"]
body:
  - type: markdown
    attributes:
      value: |
        ## 코드 리팩토링
        코드 품질 향상을 위한 리팩토링 작업을 설명해주세요.

  - type: textarea
    attributes:
      label: 🔍 리팩토링 대상
      description: 리팩토링할 코드나 컴포넌트를 명시해주세요.
      placeholder: "예: UserService 클래스, 인증 로직, 데이터 접근 계층 등"
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🤔 리팩토링 이유
      description: 왜 이 부분을 리팩토링해야 하는지 설명해주세요.
      placeholder: "현재 코드의 문제점, 개선이 필요한 이유 (성능, 가독성, 유지보수성 등)"
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🎯 개선 방향
      description: 어떻게 개선할 예정인지 설명해주세요.
      placeholder: "어떤 디자인 패턴을 적용할지, 어떤 구조로 변경할지 등"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 🔄 변경 규모
      description: 리팩토링의 변경 규모를 선택해주세요.
      options:
        - 작음 (특정 메소드/함수)
        - 중간 (단일 클래스/컴포넌트)
        - 큼 (여러 클래스/모듈)
        - 매우 큼 (시스템 구조 변경)
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 작업 내용
      description: 리팩토링 작업을 체크박스 형태로 작성해주세요.
      value: |
        - [ ] 기존 코드 분석
        - [ ] 테스트 코드 작성
        - [ ] 리팩토링 구현
        - [ ] 테스트 실행 및 검증
        - [ ] 코드 리뷰 요청
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📊 기대 효과
      description: 리팩토링 후 예상되는 개선 효과를 작성해주세요.
      placeholder: "성능 향상, 코드 복잡도 감소, 유지보수성 개선 등"
    validations:
      required: true

  - type: textarea
    attributes:
      label: ⚠️ 주의사항
      description: 리팩토링 시 주의해야 할 점을 작성해주세요.
      placeholder: "영향을 받을 수 있는 다른 모듈이나 고려해야 할 사항"
    validations:
      required: false

  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
      placeholder: "리팩토링 관련 아티클, 디자인 패턴 문서 등"
    validations:
      required: false