apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - vaultconnection.yaml
  - vaultauth.yaml
  - vaultstaticsecret-env.yaml
  - vaultstaticsecret-harbor-pull.yaml
  - deployment.yaml
  - service.yaml
