apiVersion: v1
kind: Service
metadata:
  name: seoul-fit-backend
  labels:
    app.kubernetes.io/name: seoul-fit-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: seoul-fit
spec:
  selector:
    app.kubernetes.io/name: seoul-fit-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
