-- Baseline generated from the current JPA entity model for PostgreSQL 16.
-- Flyway owns this schema in dev/prod; Hibernate only validates it.

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: air_quality; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.air_quality (
    co_value double precision,
    khai_value integer,
    no2_value double precision,
    o3_value double precision,
    pm10_24h_avg integer,
    pm10_value integer,
    pm25_24h_avg integer,
    pm25_value integer,
    so2_value double precision,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    msr_dt timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    khai_grade character varying(20),
    msr_rgn_nm character varying(100),
    msr_ste_nm character varying(100) NOT NULL
);


--
-- Name: COLUMN air_quality.co_value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.co_value IS '일산화탄소 농도 (ppm)';


--
-- Name: COLUMN air_quality.khai_value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.khai_value IS '통합대기환경지수';


--
-- Name: COLUMN air_quality.no2_value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.no2_value IS '이산화질소 농도 (ppm)';


--
-- Name: COLUMN air_quality.o3_value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.o3_value IS '오존 농도 (ppm)';


--
-- Name: COLUMN air_quality.pm10_24h_avg; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.pm10_24h_avg IS 'PM10 24시간 예측이동평균농도';


--
-- Name: COLUMN air_quality.pm10_value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.pm10_value IS 'PM10 농도 ((㎍/㎥)';


--
-- Name: COLUMN air_quality.pm25_24h_avg; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.pm25_24h_avg IS 'PM2.5 24시간 예측이동평균농도';


--
-- Name: COLUMN air_quality.pm25_value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.pm25_value IS 'PM2.5 농도 (㎍/㎥)';


--
-- Name: COLUMN air_quality.so2_value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.so2_value IS '아황솬가스 농도 (ppm)';


--
-- Name: COLUMN air_quality.msr_dt; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.msr_dt IS '측정 일시';


--
-- Name: COLUMN air_quality.khai_grade; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.khai_grade IS '통합대기환경지수 등급';


--
-- Name: COLUMN air_quality.msr_rgn_nm; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.msr_rgn_nm IS '측정소 지역명';


--
-- Name: COLUMN air_quality.msr_ste_nm; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.air_quality.msr_ste_nm IS '측정소 명';


--
-- Name: air_quality_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.air_quality ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.air_quality_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    user_id bigint,
    result character varying(20) NOT NULL,
    ip_address character varying(45),
    action character varying(50),
    event_type character varying(50) NOT NULL,
    username character varying(100),
    error_message character varying(500),
    user_agent character varying(500),
    metadata text,
    resource character varying(255),
    CONSTRAINT audit_logs_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['LOGIN_SUCCESS'::character varying, 'LOGIN_FAILURE'::character varying, 'LOGOUT'::character varying, 'PASSWORD_CHANGE'::character varying, 'ACCESS_GRANTED'::character varying, 'ACCESS_DENIED'::character varying, 'PERMISSION_CHANGED'::character varying, 'DATA_CREATE'::character varying, 'DATA_READ'::character varying, 'DATA_UPDATE'::character varying, 'DATA_DELETE'::character varying, 'SENSITIVE_DATA_ACCESS'::character varying, 'DATA_MODIFICATION'::character varying, 'SECURITY_VIOLATION'::character varying, 'RATE_LIMIT_EXCEEDED'::character varying, 'INVALID_INPUT'::character varying, 'SQL_INJECTION_ATTEMPT'::character varying, 'XSS_ATTEMPT'::character varying, 'SYSTEM_CONFIG_CHANGE'::character varying, 'ADMIN_ACTION'::character varying])::text[]))),
    CONSTRAINT audit_logs_result_check CHECK (((result)::text = ANY ((ARRAY['SUCCESS'::character varying, 'FAILURE'::character varying, 'DENIED'::character varying, 'BLOCKED'::character varying, 'ERROR'::character varying])::text[])))
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cooling_centers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cooling_centers (
    capacity integer,
    facility_year integer,
    latitude double precision,
    longitude double precision,
    map_coord_x double precision,
    map_coord_y double precision,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    area_code character varying(50),
    area_size character varying(100),
    facility_type1 character varying(100),
    facility_type2 character varying(100),
    name character varying(200) NOT NULL,
    lot_address character varying(300),
    road_address character varying(300),
    remarks text
);


--
-- Name: cooling_centers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cooling_centers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cooling_centers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cultural_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cultural_events (
    end_date date,
    latitude numeric(10,8),
    longitude numeric(11,8),
    start_date date,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_free character varying(10),
    district character varying(50) NOT NULL,
    registration_date character varying(50),
    ticket character varying(50),
    code_name character varying(100) NOT NULL,
    event_date character varying(100),
    external_id character varying(100),
    theme_code character varying(100),
    org_name character varying(200),
    use_target character varying(200),
    place character varying(500),
    title character varying(500) NOT NULL,
    homepage_addr character varying(1000),
    main_img character varying(1000),
    org_link character varying(1000),
    etc_desc text,
    player text,
    program text,
    use_fee text
);


--
-- Name: cultural_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cultural_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cultural_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cultural_reservation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cultural_reservation (
    id bigint NOT NULL,
    rcpt_bgn_dt timestamp(6) without time zone,
    rcpt_end_dt timestamp(6) without time zone,
    svc_opn_bgn_dt timestamp(6) without time zone,
    svc_opn_end_dt timestamp(6) without time zone,
    gubun character varying(50),
    pay_at_nm character varying(50),
    rev_std_day character varying(50),
    svc_stat_nm character varying(50),
    tel_no character varying(50),
    v_max character varying(50),
    v_min character varying(50),
    x_coord character varying(50),
    y_coord character varying(50),
    area_nm character varying(100),
    max_class_nm character varying(100),
    min_class_nm character varying(100),
    rev_std_day_nm character varying(100),
    svc_id character varying(100),
    place_nm character varying(200),
    svc_nm character varying(200),
    use_tgt_info character varying(200),
    dtl_cont text,
    img_url character varying(255),
    svc_url character varying(255)
);


--
-- Name: cultural_reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cultural_reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cultural_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cultural_spaces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cultural_spaces (
    latitude numeric(16,8),
    longitude numeric(16,8),
    num integer,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_free character varying(10),
    district character varying(50),
    fax character varying(50),
    open_day character varying(50),
    phone character varying(50),
    external_id character varying(100),
    subj_code character varying(100),
    airport_bus character varying(200),
    blue_line character varying(200),
    bus_stop character varying(200),
    close_day character varying(200),
    green_line character varying(200),
    red_line character varying(200),
    subway character varying(200),
    yellow_line character varying(200),
    address character varying(500) NOT NULL,
    facility_name character varying(500) NOT NULL,
    homepage character varying(1000),
    main_image character varying(1000),
    entrance_fee text,
    etc_desc text,
    facility_desc text,
    open_hour text,
    seat_count character varying(255)
);


--
-- Name: cultural_spaces_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cultural_spaces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cultural_spaces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: libraries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.libraries (
    xcnts double precision,
    ydnts double precision,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    gu_code character varying(10),
    code_value character varying(50),
    lbrry_seq_no character varying(50),
    tel_no character varying(50),
    lbrry_se_name character varying(100),
    fdrm_close_date character varying(200),
    lbrry_name character varying(200) NOT NULL,
    op_time character varying(200),
    adres character varying(300),
    hmpg_url character varying(500)
);


--
-- Name: libraries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.libraries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.libraries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_histories (
    id bigint NOT NULL,
    read_at timestamp(6) without time zone,
    sent_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    title character varying(200) NOT NULL,
    location_info character varying(500),
    message character varying(1000) NOT NULL,
    notification_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    trigger_condition character varying(255) NOT NULL,
    CONSTRAINT notification_histories_notification_type_check CHECK (((notification_type)::text = ANY ((ARRAY['EMERGENCY'::character varying, 'WEATHER'::character varying, 'TRAFFIC'::character varying, 'BIKE_SHARING'::character varying, 'CONGESTION'::character varying, 'CULTURE'::character varying, 'WELFARE'::character varying])::text[]))),
    CONSTRAINT notification_histories_status_check CHECK (((status)::text = ANY ((ARRAY['SENT'::character varying, 'READ'::character varying, 'FAILED'::character varying, 'EXPIRED'::character varying])::text[]))),
    CONSTRAINT notification_histories_trigger_condition_check CHECK (((trigger_condition)::text = ANY ((ARRAY['TEMPERATURE_HIGH'::character varying, 'TEMPERATURE_LOW'::character varying, 'HEAVY_RAIN'::character varying, 'AIR_QUALITY_BAD'::character varying, 'FINE_DUST_HIGH'::character varying, 'OZONE_WARNING'::character varying, 'TRAFFIC_JAM'::character varying, 'ROAD_CLOSURE'::character varying, 'BIKE_SHORTAGE'::character varying, 'BIKE_FULL'::character varying, 'CONGESTION'::character varying, 'SUBWAY_CROWDED'::character varying, 'CULTURAL_EVENT'::character varying, 'CULTURAL_EVENT_START'::character varying, 'EMERGENCY'::character varying, 'DISASTER'::character varying, 'WELFARE_INFO'::character varying, 'WEATHER_CHANGE'::character varying, 'INTEREST_BASED_RECOMMENDATION'::character varying, 'LOCATION_BASED'::character varying, 'TIME_BASED'::character varying, 'MANUAL'::character varying])::text[])))
);


--
-- Name: notification_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_settings (
    email_enabled boolean NOT NULL,
    is_active boolean NOT NULL,
    location_radius double precision,
    priority_threshold integer,
    push_enabled boolean NOT NULL,
    sms_enabled boolean NOT NULL,
    webhook_enabled boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    device_token character varying(255),
    email character varying(255),
    notification_type character varying(255) NOT NULL,
    phone_number character varying(255),
    quiet_hours_end character varying(255),
    quiet_hours_start character varying(255),
    trigger_condition character varying(255),
    webhook_url character varying(255),
    CONSTRAINT notification_settings_notification_type_check CHECK (((notification_type)::text = ANY ((ARRAY['EMERGENCY'::character varying, 'WEATHER'::character varying, 'TRAFFIC'::character varying, 'BIKE_SHARING'::character varying, 'CONGESTION'::character varying, 'CULTURE'::character varying, 'WELFARE'::character varying])::text[]))),
    CONSTRAINT notification_settings_trigger_condition_check CHECK (((trigger_condition)::text = ANY ((ARRAY['TEMPERATURE_HIGH'::character varying, 'TEMPERATURE_LOW'::character varying, 'HEAVY_RAIN'::character varying, 'AIR_QUALITY_BAD'::character varying, 'FINE_DUST_HIGH'::character varying, 'OZONE_WARNING'::character varying, 'TRAFFIC_JAM'::character varying, 'ROAD_CLOSURE'::character varying, 'BIKE_SHORTAGE'::character varying, 'BIKE_FULL'::character varying, 'CONGESTION'::character varying, 'SUBWAY_CROWDED'::character varying, 'CULTURAL_EVENT'::character varying, 'CULTURAL_EVENT_START'::character varying, 'EMERGENCY'::character varying, 'DISASTER'::character varying, 'WELFARE_INFO'::character varying, 'WEATHER_CHANGE'::character varying, 'INTEREST_BASED_RECOMMENDATION'::character varying, 'LOCATION_BASED'::character varying, 'TIME_BASED'::character varying, 'MANUAL'::character varying])::text[])))
);


--
-- Name: notification_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parks (
    grs80_latitude double precision,
    grs80_longitude double precision,
    latitude double precision,
    longitude double precision,
    park_idx integer,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    admin_tel character varying(50),
    management_dept character varying(100),
    zone character varying(100),
    name character varying(200) NOT NULL,
    address character varying(300),
    area character varying(500),
    guidance character varying(500),
    image_url character varying(500),
    template_url character varying(500),
    content text,
    main_equipment text,
    main_plants text,
    open_date character varying(255),
    use_reference text,
    visit_road text
);


--
-- Name: parks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: poi_search_index; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.poi_search_index (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    ref_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    ref_table character varying(50) NOT NULL,
    address text,
    aliases text,
    name character varying(255) NOT NULL,
    remark text
);


--
-- Name: poi_search_index_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.poi_search_index ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.poi_search_index_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.restaurants (
    latitude double precision,
    longitude double precision,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    lang_code_id character varying(10),
    homepage_lang character varying(50),
    post_sn character varying(50),
    name character varying(200) NOT NULL,
    phone character varying(200),
    address character varying(300),
    new_address character varying(300),
    subway_info character varying(300),
    operating_hours character varying(500),
    post_url character varying(500),
    representative_menu character varying(500),
    website character varying(500)
);


--
-- Name: restaurants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.restaurants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sports_facility_programs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sports_facility_programs (
    fee_free character varying(1),
    use_yn character varying(1),
    created_at timestamp(6) without time zone NOT NULL,
    data_date character varying(8) NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    class_end_date character varying(20),
    class_start_date character varying(20),
    capacity character varying(50),
    fax character varying(50),
    p_level character varying(50),
    parking_side character varying(50),
    tel character varying(50),
    class_time character varying(100),
    email character varying(100),
    fee character varying(100),
    subject_name character varying(100),
    week character varying(100),
    center_name character varying(200) NOT NULL,
    class_name character varying(200),
    enter_term character varying(200),
    enter_way character varying(200),
    ground_name character varying(200),
    place character varying(200),
    select_way character varying(200),
    target character varying(200),
    term character varying(200),
    address character varying(300),
    program_name character varying(300),
    homepage character varying(500),
    online_link character varying(500),
    intro text
);


--
-- Name: sports_facility_programs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sports_facility_programs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sports_facility_programs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sports_reservation_facilities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sports_reservation_facilities (
    latitude double precision,
    longitude double precision,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    district character varying(50),
    phone_number character varying(50),
    x_coordinate character varying(50),
    y_coordinate character varying(50),
    facility_type character varying(100),
    holiday character varying(100),
    facility_name character varying(200) NOT NULL,
    facility_scale character varying(200),
    operating_hours character varying(200),
    address character varying(300),
    parking_info character varying(300),
    fee_info character varying(500),
    homepage_url character varying(500),
    image_url character varying(500),
    detail_content character varying(2000),
    service_id character varying(255)
);


--
-- Name: sports_reservation_facilities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sports_reservation_facilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sports_reservation_facilities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trigger_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trigger_history (
    latitude double precision,
    longitude double precision,
    priority integer NOT NULL,
    id bigint NOT NULL,
    triggered_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    evaluation_source character varying(20),
    trigger_type character varying(50) NOT NULL,
    location_info character varying(200),
    title character varying(200) NOT NULL,
    message character varying(1000) NOT NULL,
    notification_type character varying(255) NOT NULL,
    trigger_condition character varying(255) NOT NULL,
    CONSTRAINT trigger_history_notification_type_check CHECK (((notification_type)::text = ANY ((ARRAY['EMERGENCY'::character varying, 'WEATHER'::character varying, 'TRAFFIC'::character varying, 'BIKE_SHARING'::character varying, 'CONGESTION'::character varying, 'CULTURE'::character varying, 'WELFARE'::character varying])::text[]))),
    CONSTRAINT trigger_history_trigger_condition_check CHECK (((trigger_condition)::text = ANY ((ARRAY['TEMPERATURE_HIGH'::character varying, 'TEMPERATURE_LOW'::character varying, 'HEAVY_RAIN'::character varying, 'AIR_QUALITY_BAD'::character varying, 'FINE_DUST_HIGH'::character varying, 'OZONE_WARNING'::character varying, 'TRAFFIC_JAM'::character varying, 'ROAD_CLOSURE'::character varying, 'BIKE_SHORTAGE'::character varying, 'BIKE_FULL'::character varying, 'CONGESTION'::character varying, 'SUBWAY_CROWDED'::character varying, 'CULTURAL_EVENT'::character varying, 'CULTURAL_EVENT_START'::character varying, 'EMERGENCY'::character varying, 'DISASTER'::character varying, 'WELFARE_INFO'::character varying, 'WEATHER_CHANGE'::character varying, 'INTEREST_BASED_RECOMMENDATION'::character varying, 'LOCATION_BASED'::character varying, 'TIME_BASED'::character varying, 'MANUAL'::character varying])::text[])))
);


--
-- Name: trigger_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trigger_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trigger_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trigger_history_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trigger_history_metadata (
    trigger_history_id bigint NOT NULL,
    metadata_key character varying(255) NOT NULL,
    metadata_value character varying(255)
);


--
-- Name: user_interests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_interests (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    interest_category character varying(50) NOT NULL,
    CONSTRAINT user_interests_interest_category_check CHECK (((interest_category)::text = ANY ((ARRAY['SPORTS'::character varying, 'CULTURE'::character varying, 'CULTURAL_EVENT'::character varying, 'CULTURAL_RESERVATION'::character varying, 'RESTAURANTS'::character varying, 'LIBRARY'::character varying, 'PARK'::character varying, 'SUBWAY'::character varying, 'BIKE'::character varying, 'WEATHER'::character varying, 'CONGESTION'::character varying, 'COOLING_SHELTER'::character varying])::text[])))
);


--
-- Name: user_interests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_interests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_interests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    location_latitude double precision,
    location_longitude double precision,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    oauth_token_expires_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    oauth_access_token character varying(2000),
    email character varying(255),
    location_address character varying(255),
    nickname character varying(255) NOT NULL,
    oauth_provider character varying(255),
    oauth_user_id character varying(255),
    password character varying(255),
    profile_image_url character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT users_oauth_provider_check CHECK (((oauth_provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'KAKAO'::character varying, 'NAVER'::character varying, 'LOCAL'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DELETED'::character varying, 'SUSPENDED'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: air_quality air_quality_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.air_quality
    ADD CONSTRAINT air_quality_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: cooling_centers cooling_centers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cooling_centers
    ADD CONSTRAINT cooling_centers_pkey PRIMARY KEY (id);


--
-- Name: cultural_events cultural_events_external_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cultural_events
    ADD CONSTRAINT cultural_events_external_id_key UNIQUE (external_id);


--
-- Name: cultural_events cultural_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cultural_events
    ADD CONSTRAINT cultural_events_pkey PRIMARY KEY (id);


--
-- Name: cultural_reservation cultural_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cultural_reservation
    ADD CONSTRAINT cultural_reservation_pkey PRIMARY KEY (id);


--
-- Name: cultural_spaces cultural_spaces_external_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cultural_spaces
    ADD CONSTRAINT cultural_spaces_external_id_key UNIQUE (external_id);


--
-- Name: cultural_spaces cultural_spaces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cultural_spaces
    ADD CONSTRAINT cultural_spaces_pkey PRIMARY KEY (id);


--
-- Name: libraries libraries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.libraries
    ADD CONSTRAINT libraries_pkey PRIMARY KEY (id);


--
-- Name: notification_histories notification_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_histories
    ADD CONSTRAINT notification_histories_pkey PRIMARY KEY (id);


--
-- Name: notification_settings notification_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_settings
    ADD CONSTRAINT notification_settings_pkey PRIMARY KEY (id);


--
-- Name: notification_settings notification_settings_user_id_notification_type_trigger_con_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_settings
    ADD CONSTRAINT notification_settings_user_id_notification_type_trigger_con_key UNIQUE (user_id, notification_type, trigger_condition);


--
-- Name: parks parks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parks
    ADD CONSTRAINT parks_pkey PRIMARY KEY (id);


--
-- Name: poi_search_index poi_search_index_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.poi_search_index
    ADD CONSTRAINT poi_search_index_pkey PRIMARY KEY (id);


--
-- Name: restaurants restaurants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT restaurants_pkey PRIMARY KEY (id);


--
-- Name: sports_facility_programs sports_facility_programs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sports_facility_programs
    ADD CONSTRAINT sports_facility_programs_pkey PRIMARY KEY (id);


--
-- Name: sports_reservation_facilities sports_reservation_facilities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sports_reservation_facilities
    ADD CONSTRAINT sports_reservation_facilities_pkey PRIMARY KEY (id);


--
-- Name: trigger_history_metadata trigger_history_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trigger_history_metadata
    ADD CONSTRAINT trigger_history_metadata_pkey PRIMARY KEY (trigger_history_id, metadata_key);


--
-- Name: trigger_history trigger_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trigger_history
    ADD CONSTRAINT trigger_history_pkey PRIMARY KEY (id);


--
-- Name: user_interests user_interests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_interests
    ADD CONSTRAINT user_interests_pkey PRIMARY KEY (id);


--
-- Name: user_interests user_interests_user_id_interest_category_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_interests
    ADD CONSTRAINT user_interests_user_id_interest_category_key UNIQUE (user_id, interest_category);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_audit_event_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_event_type ON public.audit_logs USING btree (event_type);


--
-- Name: idx_audit_ip_address; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_ip_address ON public.audit_logs USING btree (ip_address);


--
-- Name: idx_audit_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_timestamp ON public.audit_logs USING btree ("timestamp");


--
-- Name: idx_audit_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_username ON public.audit_logs USING btree (username);


--
-- Name: idx_cooling_centers_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cooling_centers_location ON public.cooling_centers USING btree (latitude, longitude);


--
-- Name: idx_cooling_centers_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cooling_centers_name ON public.cooling_centers USING btree (name);


--
-- Name: idx_cooling_centers_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cooling_centers_type ON public.cooling_centers USING btree (facility_type1, facility_type2);


--
-- Name: idx_event_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_category ON public.cultural_events USING btree (code_name);


--
-- Name: idx_event_category_free; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_category_free ON public.cultural_events USING btree (code_name, is_free);


--
-- Name: idx_event_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_date ON public.cultural_events USING btree (start_date, end_date);


--
-- Name: idx_event_district; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_district ON public.cultural_events USING btree (district);


--
-- Name: idx_event_district_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_district_date ON public.cultural_events USING btree (district, start_date, end_date);


--
-- Name: idx_event_external_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_external_id ON public.cultural_events USING btree (external_id);


--
-- Name: idx_event_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_location ON public.cultural_events USING btree (latitude, longitude);


--
-- Name: idx_libraries_gu; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_libraries_gu ON public.libraries USING btree (code_value);


--
-- Name: idx_libraries_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_libraries_location ON public.libraries USING btree (xcnts, ydnts);


--
-- Name: idx_libraries_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_libraries_name ON public.libraries USING btree (lbrry_name);


--
-- Name: idx_parks_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_parks_location ON public.parks USING btree (latitude, longitude);


--
-- Name: idx_parks_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_parks_name ON public.parks USING btree (name);


--
-- Name: idx_parks_zone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_parks_zone ON public.parks USING btree (zone);


--
-- Name: idx_reservation_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reservation_location ON public.cultural_reservation USING btree (x_coord, y_coord);


--
-- Name: idx_restaurants_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_restaurants_location ON public.restaurants USING btree (latitude, longitude);


--
-- Name: idx_restaurants_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_restaurants_name ON public.restaurants USING btree (name);


--
-- Name: idx_space_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_space_category ON public.cultural_spaces USING btree (subj_code);


--
-- Name: idx_space_district; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_space_district ON public.cultural_spaces USING btree (district);


--
-- Name: idx_space_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_space_location ON public.cultural_spaces USING btree (latitude, longitude);


--
-- Name: idx_sports_program_center; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sports_program_center ON public.sports_facility_programs USING btree (center_name);


--
-- Name: idx_sports_program_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sports_program_date ON public.sports_facility_programs USING btree (data_date);


--
-- Name: idx_sports_program_subject; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sports_program_subject ON public.sports_facility_programs USING btree (subject_name);


--
-- Name: idx_sports_program_use_yn; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sports_program_use_yn ON public.sports_facility_programs USING btree (use_yn);


--
-- Name: idx_sports_res_facilities_district; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sports_res_facilities_district ON public.sports_reservation_facilities USING btree (district);


--
-- Name: idx_sports_res_facilities_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sports_res_facilities_location ON public.sports_reservation_facilities USING btree (latitude, longitude);


--
-- Name: idx_sports_res_facilities_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sports_res_facilities_name ON public.sports_reservation_facilities USING btree (facility_name);


--
-- Name: idx_sports_res_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sports_res_location ON public.sports_reservation_facilities USING btree (latitude, longitude);


--
-- Name: idx_sports_res_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sports_res_name ON public.sports_reservation_facilities USING btree (facility_name);


--
-- Name: idx_sports_res_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sports_res_type ON public.sports_reservation_facilities USING btree (facility_type);


--
-- Name: idx_trigger_history_user_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trigger_history_user_time ON public.trigger_history USING btree (user_id, triggered_at);


--
-- Name: idx_trigger_history_user_type_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trigger_history_user_type_time ON public.trigger_history USING btree (user_id, trigger_type, triggered_at);


--
-- Name: idx_users_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_created_at ON public.users USING btree (created_at);


--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_email ON public.users USING btree (email);


--
-- Name: idx_users_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_location ON public.users USING btree (location_latitude, location_longitude);


--
-- Name: idx_users_oauth; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_oauth ON public.users USING btree (oauth_provider, oauth_user_id);


--
-- Name: idx_users_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_status ON public.users USING btree (status);


--
-- Name: user_interests fkdv9fflrh61wyuujfwx2yn1tb4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_interests
    ADD CONSTRAINT fkdv9fflrh61wyuujfwx2yn1tb4 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: trigger_history_metadata fkpmuy0fehjsrv8yqfascgtnrhn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trigger_history_metadata
    ADD CONSTRAINT fkpmuy0fehjsrv8yqfascgtnrhn FOREIGN KEY (trigger_history_id) REFERENCES public.trigger_history(id);


--
-- PostgreSQL database dump complete
--

